package main

import (
	"fmt"
	authRoute "meetspace_backend/auth/routes"

	"meetspace_backend/middlewares"

	// chatRoutes "meetspace_backend/chat/routes"
	// websocketRoute "meetspace_backend/chat/websocket"
	// clientRoutes "meetspace_backend/client/routes"
	userRoute "meetspace_backend/user/routes"

	"meetspace_backend/config"

	// "meetspace_backend/middlewares"
	// "net/http"

	_ "meetspace_backend/docs" // docs is generated by Swag CLI, you have to import it.

	swagger "github.com/arsmn/fiber-swagger/v2"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	_ "github.com/swaggo/fiber-swagger"
)

// @securityDefinitions.basic BasicAuth

// @securitydefinitions.oauth2.application OAuth2Application
// @tokenUrl https://example.com/oauth/token
// @scope.write Grants write access
// @scope.admin Grants read and write access to administrative information
func main() {
	// load environment
	config.LoadEnv()
	
	// initialize database connection
	config.InitDB()
	
	app := fiber.New()

	app.Static("/uploads","./uploads")
	
	// middlewares
    app.Use(logger.New())
	app.Use(middlewares.LoggerMiddleware())
	app.Use(middlewares.CorsMiddleware())
	// r.Use(middlewares.AuthMiddleware())
	
	// routes
	app.Get("/*", swagger.HandlerDefault)
	
	authRoute.AuthRouter(app)
	userRoute.UserRouter(app)
	// chatRoutes.ChatRouter(r)
	// websocketRoute.WebSocketRouter(r)
	// clientRoutes.ClientRouter(r)
	// docs.SwaggerRouter(r)

	fmt.Println("server:->", "http://localhost:8080")
    err := app.Listen(":8080")
    if err != nil {
        fmt.Println("Error starting server:", err)
    }
}
