package constants

const (
	// user events
	USER_CONNECTED = "USER_CONNECTED"
	USER_DISCONNECTED = "USER_DISCONNECTED"
	
	// chat events
	CHAT_MESSAGE_SENT = "CHAT_MESSAGE_SENT"
	CHAT_NOTIFICATION_SENT = "CHAT_NOTIFICATION_SENT"
	CHAT_NOTIFICATION_RECEIVED = "CHAT_NOTIFICATION_RECEIVED"
	CHAT_ROOM_JOINED = "CHAT_ROOM_JOINED"
	CHAT_ROOM_LEFT = "CHAT_ROOM_LEFT"

	CHAT_ROOM_JOIN = "CHAT_ROOM_JOIN"
	CHAT_ROOM_LEAVE = "CHAT_ROOM_LEAVE"

	CALL_RECEIVE = "CALL_RECEIVE"
)