definitions:
  types.AddChatGroup:
    properties:
      title:
        type: string
      user_ids:
        items:
          type: string
        type: array
    required:
    - title
    - user_ids
    type: object
  types.CreateUserData:
    properties:
      client_id:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
  types.ForgotPasswordRequest:
    properties:
      email:
        type: string
      new_password:
        type: string
    required:
    - email
    - new_password
    type: object
  types.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  types.LogoutRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  types.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  types.RegisterRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  types.SendEmailRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  types.VerifyEmailRequest:
    properties:
      email:
        type: string
      otp:
        type: string
    required:
    - email
    - otp
    type: object
  utils.Metadata:
    properties:
      api_version:
        default: v1
        type: string
      server_info:
        $ref: '#/definitions/utils.ServerInfo'
    type: object
  utils.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      metadata:
        $ref: '#/definitions/utils.Metadata'
      request_id:
        type: string
      status:
        type: string
      status_code:
        type: integer
      time_stamp:
        type: string
    type: object
  utils.ServerInfo:
    properties:
      hostname:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: MeetSpace API documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: MeetSpace API
  version: "1.0"
paths:
  /v1/auth/forgot-password:
    post:
      description: Forgot password
      parameters:
      - description: forgot password request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: forgot-password
      tags:
      - Auth
  /v1/auth/login:
    post:
      description: Login user
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login user successfully
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: login-user
      tags:
      - Auth
  /v1/auth/logout:
    post:
      description: User logout User
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.LogoutRequest'
      produces:
      - application/json
      responses:
        "204":
          description: success
        "400":
          description: Bad request
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: user-logout
      tags:
      - Auth
  /v1/auth/refresh-token:
    post:
      description: refresh jwt token
      parameters:
      - description: refresh token request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: refresh token
      tags:
      - Auth
  /v1/auth/register:
    post:
      description: Register User account
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Register user successfully
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: register-user
      tags:
      - Auth
  /v1/auth/send-email:
    post:
      description: Send email to user
      parameters:
      - description: send email request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.SendEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: send-email
      tags:
      - Auth
  /v1/auth/verify-email:
    post:
      description: Verify email otp.
      parameters:
      - description: verify email request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.VerifyEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: verify-email
      tags:
      - Auth
  /v1/chat/groups:
    post:
      description: Add Chat group
      parameters:
      - description: Add chat group details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.AddChatGroup'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: add-chat-group
      tags:
      - Chat-Group
  /v1/chat/messages:
    get:
      description: Get chat message
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: get messages successfully
        "400":
          description: Bad request
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: get chat messages
      tags:
      - Chat-Message
  /v1/chat/messages/{chat_room_id}:
    get:
      description: Get chat messages by room id
      parameters:
      - description: Chat Room ID
        in: path
        name: chat_room_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: get messages successfully
        "400":
          description: Bad request
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: get chat messages by room id
      tags:
      - Chat-Message
  /v1/chat/room/contact:
    get:
      description: UserLogin User account
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: UserLogin User account
      tags:
      - Chat-Room
  /v1/chat/rooms:
    delete:
      description: DeleteChatRoom
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: DeleteChatRoom
      tags:
      - Chat-Room
    get:
      description: GetChatRooms
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: GetChatRooms
      tags:
      - Chat-Room
    post:
      description: CreateChatRoom
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: CreateChatRoom
      tags:
      - Chat-Room
  /v1/user/check-email:
    get:
      parameters:
      - description: User create details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.CreateUserData'
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: User create
      tags:
      - User
  /v1/user/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: get user profile
      tags:
      - User
  /v1/users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: get all users
      tags:
      - User
    post:
      parameters:
      - description: User create details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.CreateUserData'
      produces:
      - application/json
      responses: {}
      security:
      - Bearer: []
      summary: User create
      tags:
      - User
    put:
      parameters:
      - description: User create details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.CreateUserData'
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: user-update
      tags:
      - User
  /v1/users/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: get user by ID
      tags:
      - User
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
